export { default as Cabinet } from './Cabinet'
export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as Resume } from './Resume'
export { default as NotFound } from './NotFound'
